(function(){function h(a,b,c,d,f,j,m,h,q){var r=a.config,n=new CKEDITOR.style(h),k={},o=[];j.forEach(function(a){for(var a=a.entries.split(";"),b=[],l=0;l<a.length;l++){var i=a[l];if(i){var i=i.split("/"),e={},d=a[l]=i[0];e[c]=b[l]=i[1]||d;k[d]=new CKEDITOR.style(h,e);k[d]._.definition.name=d}else a.splice(l--,1)}o.push(a)});a.ui.addRichCombo(b,{label:d,title:f,toolbar:"styles,"+q,allowedContent:n,requiredContent:n,panel:{css:[CKEDITOR.skin.getPath("editor")].concat(r.contentsCss),multiSelect:!1,
attributes:{"aria-label":f}},init:function(){var a=this;j.forEach(function(b,c){a.startGroup(b.label);for(var d=0;d<o[c].length;d++){var e=o[c][d];a.add(e,k[e].buildPreview(),e)}})},onClick:function(b){a.focus();a.fire("saveSnapshot");var c=this.getValue(),d=k[b];if(c&&b!=c){var i=k[c],e=a.getSelection().getRanges()[0];if(e.collapsed){var f=a.elementPath(),g=f.contains(function(a){return i.checkElementRemovable(a)});if(g){var h=e.checkBoundaryOfElement(g,CKEDITOR.START),j=e.checkBoundaryOfElement(g,
CKEDITOR.END);if(h&&j){for(h=e.createBookmark();f=g.getFirst();)f.insertBefore(g);g.remove();e.moveToBookmark(h)}else h?e.moveToPosition(g,CKEDITOR.POSITION_BEFORE_START):j?e.moveToPosition(g,CKEDITOR.POSITION_AFTER_END):(e.splitElement(g),e.moveToPosition(g,CKEDITOR.POSITION_AFTER_END),p(e,f.elements.slice(),g));a.getSelection().selectRanges([e])}}else a.removeStyle(i)}a[c==b?"removeStyle":"applyStyle"](d);a.fire("saveSnapshot");a.plugins.webfont&&a.plugins.webfont.firePresentEvent(a)},onRender:function(){a.on("selectionChange",
function(b){for(var c=this.getValue(),b=b.data.path.elements,d=0,f;d<b.length;d++){f=b[d];for(var e in k)if(k[e].checkElementMatch(f,!0,a)){e!=c&&this.setValue(e);return}}this.setValue("",m)},this)},refresh:function(){a.activeFilter.check(n)||this.setState(CKEDITOR.TRISTATE_DISABLED)}})}function p(a,b,c){var d=b.pop();if(d){if(c)return p(a,b,d.equals(c)?null:c);c=d.clone();a.insertNode(c);a.moveToPosition(c,CKEDITOR.POSITION_AFTER_START);p(a,b)}}CKEDITOR.plugins.add("webfont",{requires:"richcombo",
lang:"en",_webfonts:null,_isWebfontsPresent:null,init:function(a){var b=a.config;this._webfonts=this._parseWebFonts(b);this._isWebfontsPresent=null;var c=[{entries:b.font_names,label:a.lang.webfont.panelTitle}];b.webfont_names&&(c.push({entries:b.webfont_names,label:a.lang.webfont.webFontLabel}),this._includeWebFontCss(a));var d=[{entries:b.fontSize_sizes,label:a.lang.webfont.fontSize.panelTitle}],f=a.lang.webfont.fontSize.label,j=a.lang.webfont.fontSize.panelTitle;h(a,"Font","family",a.lang.webfont.label,
a.lang.webfont.panelTitle,c,b.font_defaultLabel,b.font_style,30);h(a,"FontSize","size",f,j,d,b.fontSize_defaultLabel,b.fontSize_style,40);var m=this;a.on("instanceReady",function(){m.firePresentEvent(a)});a.on("removeFormatCleanup",function(){setTimeout(function(){m.firePresentEvent(a)},0)})},firePresentEvent:function(a){var b=this.contentHasWebFonts(a);b!==this._isWebfontsPresent&&(this._isWebfontsPresent=b,a.fire("webfontPresent",{isPresent:this._isWebfontsPresent}))},contentHasWebFonts:function(a){for(var a=
a.document.$.getElementsByTagName("*"),b=!1,c=0;c<a.length;c++){var d=a[c];if(d.style&&d.style.fontFamily&&(b=this._webfonts.some(function(a){return 0<=d.style.fontFamily.toLowerCase().indexOf(a.toLowerCase())})))break}return b},_parseWebFonts:function(a){var b=[];a.webfont_names&&a.webfont_names.split(";").forEach(function(a){a&&(a=a.split("/"),a[0]&&b.push(a[0]))});return b},_includeWebFontCss:function(a){a=a.config;if(this._webfonts.length){var b=[];this._webfonts.forEach(function(a){b.push(a.replace(/ /g,
"+")+":400,400i,700,700i")});var c="https://fonts.googleapis.com/css?family="+b.join("|");a.contentsCss=a.contentsCss?[c].concat(a.contentsCss):[c]}}})})();CKEDITOR.config.font_names="Arial/Arial, Helvetica, sans-serif;Comic Sans MS/Comic Sans MS, cursive;Courier New/Courier New, Courier, monospace;Georgia/Georgia, serif;Lucida Sans Unicode/Lucida Sans Unicode, Lucida Grande, sans-serif;Tahoma/Tahoma, Geneva, sans-serif;Times New Roman/Times New Roman, Times, serif;Trebuchet MS/Trebuchet MS, Helvetica, sans-serif;Verdana/Verdana, Geneva, sans-serif";
CKEDITOR.config.webfont_names="";CKEDITOR.config.font_defaultLabel="";CKEDITOR.config.font_style={element:"span",styles:{"font-family":"#(family)"},overrides:[{element:"font",attributes:{face:null}}]};CKEDITOR.config.fontSize_sizes="8/8px;9/9px;10/10px;11/11px;12/12px;14/14px;16/16px;18/18px;20/20px;22/22px;24/24px;26/26px;28/28px;36/36px;48/48px;72/72px";CKEDITOR.config.fontSize_defaultLabel="";
CKEDITOR.config.fontSize_style={element:"span",styles:{"font-size":"#(size)"},overrides:[{element:"font",attributes:{size:null}}]};